name: Delphi
version: 1.0.0-SNAPSHOT
main: me.delphidevelopment.delphi.Delphi
authors: [marines4ever]
description: Custom Core Plugin
commands:
  die:
    description: Die
    aliases: [kill]
  heal:
    description: Heal +1
    aliases: []
  god:
    description: God Mode
    aliases: []
  feed:
    description: Feed player max
    aliases: [food]
  printMessageFromConfig:
    description: Print Message
  explode:
    description: Boom
  sendword:
    description: send something
  clear:
    description: Clear Inventory
    aliases: [ci]
  openinventory:
    description: Opens Inventory
    aliases: [openinv]
  gamemode:
    description: Gamemode
    aliases: [gm]
  fly:
    description: Fly
